
name: 'Build and Deploy'

on:
  push:
    branches: [ main ]

jobs:
  building:

    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://smithtimmytim.com

    permissions:
      deployments: write
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Get git output names
      id: git
      shell: bash
      run: |
        if [[ "${{ github.ref }}" != "refs/tags/"* ]]; then
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=current_branch::$HEAD_REF"
          else
            echo "::set-output name=current_branch::$REF_BRANCH"
          fi
        else
          REF=$(printf "%q" "${{ github.ref }}")
          REF_BRANCH=${REF/refs\/tags\/${{ inputs.strip_tag_prefix }}/}
          echo "::set-output name=current_branch::$(eval printf "%s" "$REF_BRANCH")"
        fi
    
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: "${{ github.token }}"
        environment: production
        ref: ${{ steps.git.outputs.current_branch }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Install npm dependencies
      run: npm install
    
    - name: Build theme
      run: npm run build --if-present
    
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        ARGS: -rltgoDzvO --exclude .git --exclude .github --exclude node_modules
        TARGET: /www/wp-content/themes/project-stardust
    
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        environment-url: http://my-app-url.com
        state: 'success'
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
    
    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github.token }}'
        environment-url: http://my-app-url.com
        state: 'failure'
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
