name: Lint

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install NPM Dependencies
      run: npm run install:npm
    - name: Lint CSS
      run: npm run lint:css
