name: "Lint PR"

on: [pull_request]

jobs:
  main:
    name: "Lint PR title"
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
