name: 'WordPress CodeSniffer'

on: pull_request

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            standard: '10up-Default'
            standard_repo: 'https://github.com/10up/phpcs-composer.git'
            repo_branch: 'master'
